### PR TITLE
Make plugin compatible with Liquibase v4.11.0 and up

### PR DESCRIPTION
**Pull request by kdeenkhoorn**
xld-liquibase-plugin updated to v5.1.0

The following changes were made:
- Dependencies are now included in the XLDP file.
- Support for rollbackVersionPrefix is added to provide more flexibility.
- Support for Liquibase v4.11.0 (and up) launcher script is added, the old way of starting Liquibase is maintained for compatibility reasons.

This pull request includes changes proposed in Pull request [#10](https://github.com/xebialabs-community/xld-liquibase-plugin/pull/10)

### CODE REVIEW

**Comment by kdeenkhoorn** [comment]
Reverted stepordering commits in the plugin for now, although it works, it does have it's affect on migration scenarios. Whenever one configures steplistoptions on an existing deployment XL Deploy sees this as an update and executes the Liquibase changelog again from the beginning. It is understandable behavior but i'm not sure if it is something you want it to do.

**Comment by kdeenkhoorn** [comment]
Found and fixed a syntax error in the test.(sh/bat).ftl

**Review by isaacsatish — APPROVED** [review]
Looks good to me

**Comment by kdeenkhoorn** [comment]
Who will perform the merge of the pullrequest ? I don't have write access to the repo.

**Pull request merged**
